---
- hosts: all
  remote_user: ec2-user
  become: true

  tasks:
  - name: ensure httpd is at the latest version
    yum: name=httpd state=latest
  - name: ensure apache is running (and enable it at boot)
    service: name=httpd state=started enabled=yes

